name: Playwright Python Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
        channel: [chrome, msedge, none]  # Only applies to chromium
        exclude:
          - browser: firefox
            channel: chrome
          - browser: firefox
            channel: msedge
          - browser: webkit
            channel: chrome
          - browser: webkit
            channel: msedge
          - browser: webkit
            channel: none
          - browser: firefox
            channel: none
          # keep chromium + chrome / msedge / none only

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps

      - name: Run Playwright Tests
        run: |
          if [ "${{ matrix.browser }}" == "chromium" ]; then
            if [ "${{ matrix.channel }}" != "none" ]; then
              pytest --browser=chromium --channel=${{ matrix.channel }}
            else
              pytest --browser=chromium
            fi
          else
            pytest --browser=${{ matrix.browser }}

      - name: Upload test results (optional)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results/
